// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/signout": {
    params: {};
  };
  "/feed": {
    params: {};
  };
  "/tweets/:id": {
    params: {
      "id": string;
    };
  };
  "/tweets/:id/like": {
    params: {
      "id": string;
    };
  };
  "/profile/:username": {
    params: {
      "username": string;
    };
  };
  "/profile/:username/edit": {
    params: {
      "username": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signup" | "/signin" | "/signout" | "/feed" | "/tweets/:id" | "/tweets/:id/like" | "/profile/:username" | "/profile/:username/edit";
  };
  "pages/Landing.tsx": {
    id: "pages/Landing";
    page: "/";
  };
  "pages/Signup.tsx": {
    id: "pages/Signup";
    page: "/signup";
  };
  "pages/Signin.tsx": {
    id: "pages/Signin";
    page: "/signin";
  };
  "pages/Signout.tsx": {
    id: "pages/Signout";
    page: "/signout";
  };
  "pages/Feed.tsx": {
    id: "pages/Feed";
    page: "/feed";
  };
  "pages/TweetDetail.tsx": {
    id: "pages/TweetDetail";
    page: "/tweets/:id";
  };
  "pages/LikeAction.tsx": {
    id: "pages/LikeAction";
    page: "/tweets/:id/like";
  };
  "pages/Profile.tsx": {
    id: "pages/Profile";
    page: "/profile/:username";
  };
  "pages/ProfileEdit.tsx": {
    id: "pages/ProfileEdit";
    page: "/profile/:username/edit";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/Landing": typeof import("./app/pages/Landing.tsx");
  "pages/Signup": typeof import("./app/pages/Signup.tsx");
  "pages/Signin": typeof import("./app/pages/Signin.tsx");
  "pages/Signout": typeof import("./app/pages/Signout.tsx");
  "pages/Feed": typeof import("./app/pages/Feed.tsx");
  "pages/TweetDetail": typeof import("./app/pages/TweetDetail.tsx");
  "pages/LikeAction": typeof import("./app/pages/LikeAction.tsx");
  "pages/Profile": typeof import("./app/pages/Profile.tsx");
  "pages/ProfileEdit": typeof import("./app/pages/ProfileEdit.tsx");
};