openapi: 3.0.0
info:
  title: Forgot Password API
  version: 1.0.0
  description: API endpoint for initiating password reset flow

paths:
  /api/auth/forgot-password:
    post:
      summary: Request password reset
      description: |
        Initiates password reset process by generating a token and sending reset email.
        Returns generic success message for both valid and invalid emails to prevent enumeration.

      tags:
        - Authentication

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address (case-insensitive, normalized to lowercase)
                  example: "user@example.com"
                  maxLength: 255

            examples:
              validRequest:
                summary: Valid email request
                value:
                  email: "user@example.com"

              invalidFormat:
                summary: Invalid email format (will fail Zod validation)
                value:
                  email: "not-an-email"

      responses:
        '200':
          description: Generic success response (same for valid/invalid email)
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: Generic success message to prevent email enumeration
                    example: "If your email is registered, you'll receive a password reset link"

        '400':
          description: Bad request (invalid email format)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid email format"
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                          example: "email"
                        message:
                          type: string
                          example: "Invalid email format"

        '429':
          description: Too many requests (rate limit exceeded)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Too many password reset requests"
                  retryAfter:
                    type: integer
                    description: Seconds until rate limit resets
                    example: 3600

        '500':
          description: Server error (email service failure, database error)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to process password reset request"

      security: []  # Public endpoint

components:
  schemas:
    ForgotPasswordRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          maxLength: 255

    ForgotPasswordResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        details:
          type: array
          items:
            type: object
